image: microsoft/dotnet:latest

stages:
    - build

before_script:
    - "dotnet nuget add source https://nuget.emzi0767.com/api/v3/index.json"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"