name: release
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Download latest NuGet (cross-platform)
      uses: NuGet/setup-nuget@v1.0.2
    - name: Add DsharpPlus
      run: nuget sources add -name DSharpPlus -source https://nuget.emzi0767.com/api/v3/index.json
    - name: Install dependencies
      run: nuget restore
    - name: Publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: sisbase.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        NUGET_SOURCE: https://api.nuget.org