name: stable
on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}
        prefix: stable
    - name : Print build number
      run: echo "Build number is 2.0.0-preview-$BUILD_NUMBER"
    - name: Download latest NuGet (cross-platform)
      uses: NuGet/setup-nuget@v1.0.2
    - name: Add DsharpPlus
      run: nuget sources add -name DSharpPlus -source https://nuget.emzi0767.com/api/v3/index.json
    - name: Install dependencies
      run: nuget restore
    - name: Build & Pack
      run: nuget pack -Version 2.0.0 -Suffix preview-$BUILD_NUMBER -Build -Prop Configuration=Release
    - name: Push Nupkg to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        # Path of NuPkg
        nupkg-path: '*.nupkg'
        # package repository owner
        repo-owner: siscodeorg
        # user account
        gh-user: roridev
        # access token
        token: ${{secrets.github_token}}
        # skip publishing duplicated package(s)
        skip-duplicate: true
